@ECHO OFF
rem 9:27 2019/2/13
cd /d "%~dp0"
Rd "%WinDir%\system32\test_permissions" >NUL 2>NUL
Md "%WinDir%\System32\test_permissions" 2>NUL||(Echo 请使用右键管理员身份运行！&&Pause >nul&&Exit)
Rd "%WinDir%\System32\test_permissions" 2>NUL
SetLocal EnableDelayedExpansion
TITLE Chrome Clean

taskkill /im chrome.exe -f

::360cse
taskkill /im 360chrome.exe -f
taskkill /im wow_helper.exe -f
set ver=9.5.0.138
del /f /q "%ver%\360bdoctor.exe"
del /f /q "%ver%\safe505.dll"
del /f /q "%ver%\sesafe.dll"
del /f /q "%ver%\smart_preheat.dll"
del /f /q "%ver%\smartpreheat64.dll"
del /f /q "%ver%\360BDoctorExt\bin\360feedback.exe"
rd /s /q  "%ver%\installer"
md "%ver%\debug.log"
::-
del /f /q "User Data\BrowserMetrics-spare.pma"
del /f /q "User Data\CrashpadMetrics-active.pma"
del /f /q "User Data\CrashpadMetrics.pma*"
del /f /q "User Data\Local State"
del /f /q "User Data\Safe Browsing Channel IDs"
del /f /q "User Data\Safe Browsing Channel IDs-journal"
del /f /q "User Data\Safe Browsing Cookies"
del /f /q "User Data\Safe Browsing Cookies-journal"
del /f /q "User Data\chrome_shutdown_ms.txt"
::--
rd /s /q "User Data\Avatars"
rd /s /q "User Data\BrowserMetrics"
rd /s /q "User Data\CertificateRevocation"
rd /s /q "User Data\CertificateTransparency"
rd /s /q "User Data\Crashpad"
rd /s /q "User Data\FileTypePolicies"
rd /s /q "User Data\InterventionPolicyDatabase"
rd /s /q "User Data\MEIPreload"
rd /s /q "User Data\OriginTrials"
rd /s /q "User Data\PepperFlash"
rd /s /q "User Data\PnaclTranslationCache"
rd /s /q "User Data\RecoveryImproved"
rd /s /q "User Data\SSLErrorAssistant"
rd /s /q "User Data\Safe Browsing"
rd /s /q "User Data\ShaderCache"
rd /s /q "User Data\Stability"
rd /s /q "User Data\Subresource Filter"
rd /s /q "User Data\SwReporter"
rd /s /q "User Data\ThirdPartyModuleList32"
rd /s /q "User Data\Webstore Downloads"
rd /s /q "User Data\WidevineCdm"
rd /s /q "User Data\pnacl"
::---
del /f /q "User Data\Default\*.ldb"
del /f /q "User Data\Default\*.log"
del /f /q "User Data\Default\Affiliation Database"
del /f /q "User Data\Default\Affiliation Database-journal"
del /f /q "User Data\Default\Cookies"
del /f /q "User Data\Default\Current Session"
del /f /q "User Data\Default\Current Tabs"
del /f /q "User Data\Default\Extension Cookies"
del /f /q "User Data\Default\Extension Cookies-journal"
del /f /q "User Data\Default\Favicons"
del /f /q "User Data\Default\Google Profile Picture.png"
del /f /q "User Data\Default\History Provider Cache"
del /f /q "User Data\Default\History"
del /f /q "User Data\Default\LOG"
del /f /q "User Data\Default\LOG.old"
del /f /q "User Data\Default\Last Session"
del /f /q "User Data\Default\Last Tabs"
del /f /q "User Data\Default\Login Data"
del /f /q "User Data\Default\Network Action Predictor"
del /f /q "User Data\Default\Network Persistent State"
del /f /q "User Data\Default\Origin Bound Certs"
del /f /q "User Data\Default\Origin Bound Certs-journal"
del /f /q "User Data\Default\QuotaManager"
del /f /q "User Data\Default\QuotaManager-journal"
del /f /q "User Data\Default\README"
del /f /q "User Data\Default\Secure Preferences"
del /f /q "User Data\Default\Shortcuts"
del /f /q "User Data\Default\Shortcuts-journal"
del /f /q "User Data\Default\Top Sites"
del /f /q "User Data\Default\Translate Ranker Model"
del /f /q "User Data\Default\TransportSecurity"
del /f /q "User Data\Default\Visited Links"
del /f /q "User Data\Default\Web Data"
del /f /q "User Data\Default\page_load_capping_opt_out.db"
del /f /q "User Data\Default\previews_opt_out.db"
::----
::rd /s /q "User Data\Default\Local Extension Settings"
rd /s /q "User Data\Default\Application Cache"
rd /s /q "User Data\Default\Accounts"
rd /s /q "User Data\Default\AutofillStrikeDatabase"
rd /s /q "User Data\Default\Managed Extension Settings"
rd /s /q "User Data\Default\BudgetDatabase"
rd /s /q "User Data\Default\Cache"
rd /s /q "User Data\Default\Code Cache"
rd /s /q "User Data\Default\Download Service"
rd /s /q "User Data\Default\Extension Rules"
rd /s /q "User Data\Default\Extension State"
rd /s /q "User Data\Default\Feature Engagement Tracker"
rd /s /q "User Data\Default\File System"
rd /s /q "User Data\Default\GCM Store"
rd /s /q "User Data\Default\GPUCache"
rd /s /q "User Data\Default\IndexedDB"
rd /s /q "User Data\Default\JumpListIconsMostVisited"
rd /s /q "User Data\Default\JumpListIconsRecentClosed"
rd /s /q "User Data\Default\Local Storage"
rd /s /q "User Data\Default\Media Cache"
rd /s /q "User Data\Default\Pepper Data"
rd /s /q "User Data\Default\Platform Notifications"
rd /s /q "User Data\Default\Service Worker"
rd /s /q "User Data\Default\Session Storage"
rd /s /q "User Data\Default\Site Characteristics Database"
rd /s /q "User Data\Default\Storage"
rd /s /q "User Data\Default\Sync Data"
rd /s /q "User Data\Default\Sync Extension Settings"
rd /s /q "User Data\Default\Thumbnails"
rd /s /q "User Data\Default\VideoDecodeStats"
rd /s /q "User Data\Default\WebRTC Logs"
rd /s /q "User Data\Default\blob_storage"
rd /s /q "User Data\Default\data_reduction_proxy_leveldb"
rd /s /q "User Data\Default\databases"

::Vivaldi
taskkill /im vivaldi.exe -f
taskkill /im update_notifier.exe -f
reg delete "HKCU\Software\Vivaldi" /f
rd /s /q "%AppData%\Vivaldi"
rd /s /q "%userprofile%\AppData\Local\Vivaldi"
::del /f /q "User Data\Default\Bookmarks"
del /f /q "User Data\Default\Bookmarks.bak"
del /f /q "User Data\Default\Calendar"
del /f /q "User Data\Default\Calendar-journal"
del /f /q "User Data\Default\Contacts"
del /f /q "User Data\Default\Contacts-journal"
del /f /q "User Data\Default\Cookies-journal"
del /f /q "User Data\Default\Favicons-journal"
del /f /q "User Data\Default\History-journal"
del /f /q "User Data\Default\Login Data-journal"
del /f /q "User Data\Default\Network Action Predictor-journal"
del /f /q "User Data\Default\Notes.bak"
del /f /q "User Data\Default\Top Sites-journal"
del /f /q "User Data\Default\Web Data-journal"
del /f /q "User Data\Default\page_load_capping_opt_out.db-journal"
del /f /q "User Data\Default\previews_opt_out.db-journal"
rd /s /q "User Data\Default\JumpListIconsVivaldiSpeedDials"
::rd /s /q "User Data\Default\Local App Settings"
rd /s /q "User Data\Default\Web Applications"

exit
